# Generation Pathes

entities_path: /Users/monakov/Development/rendez-vous-ios/Common/Models/Models/Entity
entries_path: /Users/monakov/Development/rendez-vous-ios/Common/Models/Models/Entry
enums_path: /Users/monakov/Development/rendez-vous-ios/Common/Models/Models/Shared

# Project Info

# Path to .xcodeproj file where generated files are supposed to be added
project_path: /Users/monakov/Development/rendez-vous-ios/Common/Models/Models.xcodeproj

# Name of root main project directory. Used to detect correct subgroup in project tree
project_main_group: Models

# Targets in provided Project for generated files
targets:
    - Models

# Types of models supposed to be generated, current values: \"nodeKitEntry\" and \"nodeKitEntity\"
generation_types:
  - nodeKitEntity
  - nodeKitEntry
  - enum

# Flag responsible for properties and models comments
generate_descriptions: true

# Resources Pathes

# Path to template files. Default value: ./Templates
templates_path: /Users/monakov/Development/SurfGen/Templates

# Path to black list file. Model names in this list will be ignored during generation proccess
# black_list_path: .

# If your spec is located at private repo on gitlab you can specify personal access token (for more info see https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html)
gitlab_token: HkDpUKE87yWEHET-_Mns
