name: CI

on: 
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pod install
      - name: Build and test
        run: 
          cd surfgen &&  xcodebuild clean test -project surfgen.xcodeproj -scheme "surfgen"
