name: CI

on: 
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Pod install
        run:
          pod install
      - name: Build and test
        run: 
          xcodebuild -workspace ModelsCodeGeneration.xcworkspace -scheme ModelsCodeGeneration -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 11' test
